### ISSUE TITLE
access

### ISSUE THREAD

**Issue by jinncoder** [MythicC2Profiles/websocket#1]
Can I have dev. access to push a branch?

I would fork - but y'all have LFS enabled, and forks with LFS don't work well... Unless you pay Micro$oft...

```bash
can not upload new objects to public fork 
```

**Comment by jinncoder** [comment]
The branch I'll push works with the agent I wrote https://github.com/ArchiMoebius/zippy (Linux support - mac/win. support lacking) as it follows the https://docs.mythic-c2.net/customizing/c2-related-development/c2-profile-code/agent-side-coding/agent-message-format docs. that I could find.

**Comment by jinncoder** [comment]
@its-a-feature

**Comment by its-a-feature** [comment]
Sorry, this fell off my radar! I just invited you to the repo. Would you like to be added to the MythicAgents organization for your zippy agent to be hosted?

**Comment by jinncoder** [comment]
No worries ; )

Yeah - that'd be cool - thanks!

**Comment by its-a-feature** [comment]
Ok, invited you to the other organization for your agent. Looking forward to seeing your updates :)
